In [14]:
import pandas as pd
import numpy as np

data=pd.read_csv("Iris.csv")
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [24]:
for i in data.columns:
  if(i != "Id" and i!="Species"):
    data[i] = data[i] - data[i].mean() / data[i].std()
print(data)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1      -0.491419      5.657432      -1.653171     -0.883222   
1      2      -0.691419      5.157432      -1.653171     -0.883222   
2      3      -0.891419      5.357432      -1.753171     -0.883222   
3      4      -0.991419      5.257432      -1.553171     -0.883222   
4      5      -0.591419      5.757432      -1.653171     -0.883222   
..   ...            ...           ...            ...           ...   
145  146       1.108581      5.157432       2.146829      1.216778   
146  147       0.708581      4.657432       1.946829      0.816778   
147  148       0.908581      5.157432       2.146829      0.916778   
148  149       0.608581      5.557432       2.346829      1.216778   
149  150       0.308581      5.157432       2.046829      0.716778   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [29]:
cov_matrix = data.drop(columns=["Id" , "Species"]).cov()
print(cov_matrix)

               SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
SepalLengthCm       0.685694     -0.039268       1.273682      0.516904
SepalWidthCm       -0.039268      0.188004      -0.321713     -0.117981
PetalLengthCm       1.273682     -0.321713       3.113179      1.296387
PetalWidthCm        0.516904     -0.117981       1.296387      0.582414


In [61]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print(eigenvalues)
print(eigenvectors)

[4.22484077 0.24224357 0.07852391 0.02368303]
[[ 0.36158968 -0.65653988 -0.58099728  0.31725455]
 [-0.08226889 -0.72971237  0.59641809 -0.32409435]
 [ 0.85657211  0.1757674   0.07252408 -0.47971899]
 [ 0.35884393  0.07470647  0.54906091  0.75112056]]


In [68]:
sorted_i = np.argsort(eigenvalues)
print(sorted_i)

sorted_eigenvalues = eigenvalues[sorted_i]
sorted_eigenvectors = eigenvectors[:, sorted_i]

print("Sorted Eigenvalues:\n", sorted_eigenvalues)
print("\nSorted Eigenvectors:\n", sorted_eigenvectors)

[3 2 1 0]
Sorted Eigenvalues:
 [0.02368303 0.07852391 0.24224357 4.22484077]

Sorted Eigenvectors:
 [[ 0.31725455 -0.58099728 -0.65653988  0.36158968]
 [-0.32409435  0.59641809 -0.72971237 -0.08226889]
 [-0.47971899  0.07252408  0.1757674   0.85657211]
 [ 0.75112056  0.54906091  0.07470647  0.35884393]]


In [69]:
d =2
top = eigenvectors[:,:d]
print(top)

projdata = data.drop(columns=["Id" , "Species"]).dot(top)
print(projdata)

[[ 0.36158968 -0.65653988]
 [-0.08226889 -0.72971237]
 [ 0.85657211  0.1757674 ]
 [ 0.35884393  0.07470647]]
            0         1
0   -2.376122 -4.162218
1   -2.407305 -3.666054
2   -2.581734 -3.698265
3   -2.438352 -3.524487
4   -2.420508 -4.169536
..        ...       ...
145  2.252102 -4.023026
146  1.833749 -3.460590
147  2.072131 -3.914130
148  2.209714 -3.951488
149  1.697751 -3.552724

[150 rows x 2 columns]
